replicaCount: 1

image:
  repository: orthancteam/orthanc
  pullPolicy: Always
  tag: "24.3.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "orth-service"

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  httpPort: 8042
  dicomPort: 4242

resources:
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: orthanc.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

env:
  - name: DB_ADDR
    value: "postgres-hostname"
  - name: DB_PORT
    value: "5432"
  - name: DB_DBNAME
    value: "orthanc"
  - name: DB_USERNAME
    value: "orthanc_user"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pg-connection-secret
        key: 'password'

orthancJson: |
  {  
    "Name" : "Orthanc",
    "RemoteAccessAllowed" : true,
    "SslEnabled" : false,
    "AuthenticationEnabled" : true,
    "RegisteredUsers" : {
      "admin" : "orthanc"
    },
    "DicomTlsEnabled" : false,
    "DicomTlsRemoteCertificateRequired" : false,
    "PostgreSQL" : {
      "EnableIndex" : true,
      "EnableStorage" : true,
      "Host" : "${DB_ADDR}",
      "Port" : ${DB_PORT},
      "Database" : "${DB_DBNAME}",
      "Username" : "${DB_USERNAME}",
      "Password" : "${DB_PASSWORD}",
      "EnableSsl" : true,
      "Lock" : false
    },
    "Plugins" : [
      "/usr/share/orthanc/plugins-available/libOrthancPostgreSQLIndex.so",
      "/usr/share/orthanc/plugins-available/libOrthancPostgreSQLStorage.so",
      "/usr/share/orthanc/plugins-available/libOrthancWebViewer.so"
    ]
  }
