replicaCount: 1

image:
  repository: orthancteam/orthanc
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "orth-service"

podAnnotations: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  httpPort: 8042
  dicomPort: 4242

resources:
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: orthanc.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

env:
  - name: DB_ADDR
    valueFrom:
      secretKeyRef:
        name: pg-connection-secret
        key: 'password'
  - name: DB_PORT
    valueFrom:
      secretKeyRef:
        name: pg-connection-secret
        key: 'password'
  - name: DB_DBNAME
    valueFrom:
      secretKeyRef:
        name: pg-connection-secret
        key: 'password'
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: pg-connection-secret
        key: 'password'
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pg-connection-secret
        key: 'password'
        
extraVolumes: []
extraVolumeMounts: []

orthancJson: |
  {  
    "Name" : "Orthanc",
    "RemoteAccessAllowed" : true,
    "SslEnabled" : false,
    "AuthenticationEnabled" : true,
    "RegisteredUsers" : {
      "admin" : "orthanc"
    },
    "DicomTlsEnabled" : false,
    "DicomTlsRemoteCertificateRequired" : false,
    "PostgreSQL" : {
      "EnableIndex" : true,
      "EnableStorage" : true,
      "Host" : "${DB_ADDR}",
      "Port" : ${DB_PORT},
      "Database" : "${DB_DBNAME}",
      "Username" : "${DB_USERNAME}",
      "Password" : "${DB_PASSWORD}",
      "EnableSsl" : true,
      "Lock" : false
    },
    "Plugins" : [
      "/usr/share/orthanc/plugins-available/libOrthancPostgreSQLIndex.so",
      "/usr/share/orthanc/plugins-available/libOrthancPostgreSQLStorage.so",
      "/usr/share/orthanc/plugins-available/libOrthancWebViewer.so"
    ]
  }

auth_service:
  enabled: false

  image:
    repository: "orthancteam/orthanc-auth-service"
    tag: "24.2.0"

  env: []

  extraVolumeMounts: []
  
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits: {}

  permissionsJson: |
    {
      "roles" : {
        "admin-role": {
          "permissions": ["all"],
          "authorized_labels": ["*"]
        },
        "doctor-role": {
          "permissions":["view", "download", "share", "send"],
          "authorized_labels": ["*"]
        },
        "external-role": {
          "permissions":["view", "download"],
          "authorized_labels": ["external"]
        }
      }
    }