apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  releaseName: kiali-operator
  chart:
    spec:
      chart: kiali-operator 
      sourceRef:
        kind: HelmRepository
        name: kiali 
        namespace: flux-system
      version: "1.48.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    cr:
      create: true
      name: kiali-cr
      namespace: monitoring
      spec:
        istio_namespace: "istio-system"
        istio_component_namespaces:
          prometheus: monitoring
        auth:
          strategy: anonymous
        deployment:
          accessible_namespaces:
          - '**'
          ingress_enabled: false
        external_services:
          prometheus:
            cache_duration: 10
            cache_enabled: true
            url: "http://prom-kube-prometheus-stack-prometheus.monitoring:9090"
          grafana:
            enabled: true
            auth:
              type: "basic"
              username: "admin"
              password: "prom-operator"
            in_cluster_url: "http://prom-grafana.monitoring:80"
            url: "http://prom-grafana.monitoring:80"
          istio:
            component_status:
              components:
              - app_label: "istiod"
                is_core: true
                is_proxy: false
              - app_label: "istio-ingressgateway"
                is_core: true
                is_proxy: true
              - app_label: "istio-egressgateway"
                is_core: false
                is_proxy: true
              enabled: true
            config_map_name: "istio"
            istio_deployment_name: "istiod"
          server:
            web_root: "/kiali"
          tracing:
            enabled: false
        istio_labels:
          app_label_name: "app"
          injection_label_name: "istio-injection"
          injection_label_rev:  "istio.io/rev"
          version_label_name: "version"
