apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orthweb-cert
  namespace: orthweb 
spec:
  commonName: orthweb.com 
  secretName: orthweb-secret
  duration: 2160h
  renewBefore: 72h
  subject:
    organizations:
      - digihunch
  dnsNames:
    - web.orthweb.com
    - dicom.orthweb.com
  privateKey:
    algorithm: RSA 
    size: 2048 
  issuerRef:
    name: my-ca-issuer
    kind: Issuer
    group: cert-manager.io
