kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-app
  namespace: orthweb
data:
  orthanc.json: |
    {
      "Name" : "Orthanc Configuration",
      "RemoteAccessAllowed" : true,
      "SslEnabled" : true,
      "SslCertificate" : "tls.pem",
      "PostgreSQL" : {
        "EnableIndex" : true,
        "EnableStorage" : true,
        "Host" : "${DB_ADDR}",
        "Port" : ${DB_PORT},
        "Database" : "orthancdb",
        "Username" : "${DB_USERNAME}",
        "Password" : "${DB_PASSWORD}",
        "EnableSsl" : true,
        "Lock" : false
      },
      "Plugins" : [
        "/usr/local/share/orthanc/plugins/libOrthancPostgreSQLIndex.so",
        "/usr/local/share/orthanc/plugins/libOrthancPostgreSQLStorage.so",
        "/usr/local/share/orthanc/plugins/libOrthancWebViewer.so"
      ]
    }
  db.engine: "postgres"
  db.port: "5432"
  db.addr: "postgres-ha-postgresql-ha-pgpool.orthweb.svc.cluster.local"
  db.user: postgres
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-dbinit
  namespace: orthweb
data:
  db_create.sql: |
    CREATE DATABASE orthancdb;
