apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: orthweb-cluster
  region: us-east-1
  version: "1.20"
privateCluster:
  enabled: false
  additionalEndpointServices:
  - "cloudformation"
  - "autoscaling"
  - "logs"
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true 
  nat: 
    gateway: Single
managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.micro 
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    privateNetworking: true
    volumeSize: 80
    ssh:
      allow: true 
  - name: managed-ng-2
    instanceType: t3.micro
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    privateNetworking: true
    volumeSize: 80
    ssh:
      allow: true

