apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-orthweb
resources:
  - namespace.yaml
  - ../base/certificates
  - ../base/istio-service
  - ../base/postgres
transformers:
  - labels.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames 
        value:
        - web.dev.orthweb.com 
        - dicom.dev.orthweb.com
    target:
      kind: Certificate
      name: orthweb-cert
