apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: postgresql-ha
  namespace: flux-system
spec:
  chart: postgresql-ha
  version: 14.1.0 
  sourceRef:
    name: bitnami
    kind: HelmRepository
  interval: 5m
