apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system 
spec:
  url: https://istio-release.storage.googleapis.com/charts 
  interval: 10m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: base 
  namespace: flux-system
spec:
  chart: base 
  version: 1.12.0 
  sourceRef:
    name: istio
    kind: HelmRepository
  interval: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: istiod
  namespace: flux-system
spec:
  chart: istiod 
  version: 1.12.0 
  sourceRef:
    name: istio
    kind: HelmRepository
  interval: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: gateway
  namespace: flux-system
spec:
  chart: gateway 
  version: 1.12.0 
  sourceRef:
    name: istio
    kind: HelmRepository
  interval: 5m
