apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tst-orthweb
resources:
  - namespace.yaml
  - ../base/certificates
  - ../base/istio-service
  - ../base/postgres
transformers:
  - labels.yaml
