kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-dbinit
  namespace: {{ $.Release.Namespace | quote }}
data:
  db_create.sql: |
    CREATE DATABASE orthancdb;
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-app
  namespace: {{ $.Release.Namespace | quote }}
data:
  orthanc.json: | 
    {{- $.Files.Get "orthanc.json" | nindent 4 }}
  db.engine: "postgres"
  db.port: "5432"
  db.addr: "{{ $.Release.Name }}-postgresql-ha-pgpool.{{ $.Release.Namespace }}.svc.cluster.local"
  db.user: postgres
