kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-dbinit
  namespace: {{ $.Release.Namespace | quote }}
data:
  db_create.sql: |
    CREATE DATABASE orthancdb;
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-app
  namespace: {{ $.Release.Namespace | quote }}
data:
{{- if .Values.auth_service.enabled }}
  permissions.json: |
    {{ .Values.auth_service.permissionsJson | nindent 4 }}
{{- end }}
  orthanc.json: | 
    {{ .Values.orthancJson | nindent 4 }}