apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orthanc.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "orthanc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "orthanc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "orthanc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["/run/secrets/"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: dicom
              containerPort: {{ .Values.service.dicomPort }} 
              protocol: TCP
          
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: app-cm-vol
              mountPath: "/run/secrets/orthanc.json"
              subPath: "orthanc.json"
              readOnly: true
          {{- if .Values.extraVolumeMounts }}
    {{ toYaml .Values.extraVolumeMounts | indent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /app/explorer.html
              port: http
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: Basic {{ "admin:orthanc" | b64enc }}  
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /app/explorer.html
              port: http
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: Basic {{ "admin:orthanc" | b64enc }}  
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      automountServiceAccountToken: false
      volumes:
      - name: app-cm-vol
        configMap:
          name: orthanc-app
          defaultMode: 0755
        {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8}}
        {{- end }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
