kind: ConfigMap
apiVersion: v1
metadata:
  name: orthanc-dbinit
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#  annotations:
#    "helm.sh/hook": pre-install
#    "helm.sh/hook-weight": "-5"
#    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
data:
  db_create.sql: |
    CREATE DATABASE orthancdb;
