apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-ca
#  namespace: istio-system
spec:
  isCA: true
  commonName: my-ca
  secretName: ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
#  namespace: istio-system
spec:
  ca:
    secretName: ca-secret
